# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ExodusOS
currentbranch: squirrel

description: >- # this means to ignore newlines until "baseurl:"
  This is the download center for all the builds for ExodusOS ROM.
  Including various features from other projects and some interesting
  system apps.
keywords: rom, android, craftrom, craft, mokee, redmi, xiaomi, poco, exodus, exodusos
baseurl: "" # the subpath of your site, e.g. /blog
url:  https://exodus.craft-rom.pp.ua
permalink: /:title/
twitter_username: jekyllrb
github_username:  jekyll

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-71613593-4

# Includes an icon in the footer for each username you enter
footer-links:
  email: craftrom.help@gmail.com
  telegram: exodusos
  github: ExodusOS
  
# Build settings
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  auto_ids: true
  hard_wrap: false
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
    
highlighter: rouge
# library used for syntax highlighting

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  sourcemap: true

plugins:
  - jekyll-feed

# Collections
collections:
    devices:
    devicesbeta:
    changelog:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .idea/
  - .gitignore
  - Dockerfile
  - Dockerfile.deploy
  - CNAME
  
# Plugins
# Use the following plug-ins
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem